# Prettier configuration
plugins:
  - prettier-plugin-java
overrides:
  - files:
      - "*.java"
    options:
      printWidth: 120
      tabWidth: 2
      useTabs: true
      trailingComma: "none"
      objectWrap: "preserve"
