application:
  security:
    jwt:
      secret-key: Bx4MeizkOfmx5buS0AeRdfWkK1H4GI8abShDqtZq6gA=
      time:
        expiration: 3600
server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 20
    max-connections: 8192
    accept-count: 100
    connection-timeout: 2000
spring:
  application:
    name: tonys
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/dbadon_dev?createDatabaseIfNotExist=true
    username: postgres
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000
      connection-timeout: 2000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        event:
          merge:
            "[entity_copy_observer]": allow
    show-sql: true
